### ISSUE TITLE
Provide more output on start failure

### ISSUE THREAD

**Issue by mawigh** [pc2/slurm_jupyter_kernel#6]
It would be great if we can show more output on Jupyter Notebook/JupyterLab or external Applications like Visual Studio Code if a Jupyter kernel cannot be started.

**Comment by bjudkewitz** [comment]
+1 !
Kernel doesn't start/connect and I don't know how to troubleshoot. No clues in the jupyterhub output.

**Comment by mawigh** [comment]
The idea is to create a Jupyter [kernel provisioner](https://jupyter-client.readthedocs.io/en/stable/provisioning.html).

I have implemented this in the branch [custom-kernel-manager](https://github.com/pc2/slurm_jupyter_kernel/tree/custom_kernel_manager).

@bjudkewitz What is your setup? Do you have a local JupyterHub instance running or are you using your institute's JupyterHub?

**Comment by mawigh** [comment]
The kernel provisioner will be registered using the entry_points inside _setup.py_
Just install the package inside your environment with
`python3 -m pip install git+https://github.com/pc2/slurm_jupyter_kernel.git@custom_kernel_manager`

Check the start parameters with `slurmkernel list -v`and try out activate the debug mode using `--debug`

**Comment by bjudkewitz** [comment]
Thank you very much for your advice! I installed it and sadly still get "Unhandled Error" when I try to start the remote kernel, but I haven't been able to use `--debug` with `slurmkernel`. How do I activate debug mode?

**Comment by mawigh** [comment]
How is your JupyterHub environment set up?
If you want to use Jupyter notebooks on your local machine you just need to install `notebook` and maybe `jupyterlab` as interface. JupyterHub is for multi-user purposes.

Start JupyterLab (with debug mode) using `jupyter lab --debug` and select your Slurm kernel.
